name: Publish

on:
  push:
    tags:
      - 'v*'
    branches:
      - master
    paths:
      - 'package.json'
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Run in dry-run mode (no actual publishing)'
        required: false
        default: 'false'

jobs:
  check-version:
    name: Check version bump
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get current and previous versions
        id: versions
        run: |
          CURRENT_VERSION=$(jq -r '.version' package.json)
          echo "current=$CURRENT_VERSION" >> $GITHUB_OUTPUT

          # Get previous version from last tag
          PREVIOUS_TAG=$(git tag --sort=-creatordate | head -1)
          if [ -z "$PREVIOUS_TAG" ]; then
            PREVIOUS_VERSION="0.0.0"
          else
            PREVIOUS_VERSION=${PREVIOUS_TAG#v}
          fi
          echo "previous=$PREVIOUS_VERSION" >> $GITHUB_OUTPUT

      - name: Validate version bump
        run: |
          CURRENT="${{ steps.versions.outputs.current }}"
          PREVIOUS="${{ steps.versions.outputs.previous }}"

          if [ "$CURRENT" = "$PREVIOUS" ]; then
            echo "❌ Error: Version not bumped! Current: $CURRENT, Previous: $PREVIOUS"
            echo "Please update package.json version before merging."
            exit 1
          fi

          echo "✅ Version check passed: $PREVIOUS → $CURRENT"

  validate:
    name: Validate before publish
    needs: check-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run type check
        run: npx tsc --noEmit

      - name: Run tests
        run: npm test

      - name: Build library
        run: npm run build

  publish-npm:
    name: Publish to npm
    needs: validate
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run build

      - name: Publish to npm (dry-run)
        if: ${{ github.event.inputs.dry-run == 'true' }}
        run: npm publish --dry-run --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to npm
        if: ${{ github.event.inputs.dry-run != 'true' }}
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-docs:
    name: Publish documentation
    needs: validate
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate landing page and API documentation
        run: npm run docs

      - name: Prepare deployment directory
        run: |
          mkdir -p deploy-docs
          cp index.html deploy-docs/index.html
          cp -r docs-api/* deploy-docs/
          touch deploy-docs/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy-docs
          publish_branch: gh-pages
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'

  create-release:
    name: Create GitHub Release
    needs: [publish-npm, publish-docs]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version
        id: get_version
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
            TAG_NAME="${GITHUB_REF#refs/tags/}"
          else
            VERSION=$(jq -r '.version' package.json)
            TAG_NAME="v${VERSION}"
          fi
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_OUTPUT

      - name: Check if tag exists
        id: tag_check
        run: |
          if git ls-remote --tags origin "${{ steps.get_version.outputs.TAG_NAME }}" | grep -q "refs/tags/${{ steps.get_version.outputs.TAG_NAME }}$"; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create git tag (if not from tag push)
        if: steps.tag_check.outputs.exists == 'false'
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git tag ${{ steps.get_version.outputs.TAG_NAME }}
          git push origin ${{ steps.get_version.outputs.TAG_NAME }}

      - name: Generate changelog
        id: changelog
        run: |
          PREVIOUS_TAG=$(git tag --sort=-creatordate | sed -n '2p')
          if [ -z "$PREVIOUS_TAG" ]; then
            PREVIOUS_TAG=$(git rev-list --max-parents=0 HEAD)
          fi
          echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
          git log ${PREVIOUS_TAG}..HEAD --pretty=format:"- %s (%h)" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.TAG_NAME }}
          release_name: Release v${{ steps.get_version.outputs.VERSION }}
          body: |
            ## Changes in v${{ steps.get_version.outputs.VERSION }}

            ${{ steps.changelog.outputs.CHANGELOG }}

            ### Installation
            ```bash
            npm install @micskeil/postmessage-rpc@${{ steps.get_version.outputs.VERSION }}
            ```

            ### Documentation
            [API Documentation](https://micskeil.github.io/postmessage-rpc/)
          draft: false
          prerelease: false
